// The following code corresponds to the opinion formation model presented in "Social polarization promoted by
// higher order interactions" (https://doi.org/10.48550/arXiv.2507.12325)
// The most updated version of this code can be found in the repository: https://github.com/hperezmartinez/opinionHO
//
// This code acts as a joiner for the multiple output files generated by code "opinions_HO.c", merging all txt files
// together into a single file for a given network structure.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

// The following lines mark the network used
// Only one line can be uncommented at any given time
#define RSC
//#define HGMRI
//#define HG

#define HEADER_LENGTH 200

int main()
{
    char network_type[10];
    int i, header, stat, N_steps;
    double mean_opinion, dev_opinion, exposure;
    double lmbda_min, lmbda_max, delta_lmbda, lmbda;
    double beta_min, beta_max, delta_beta, beta;
    double lmbda_file, lmbda_T_file, beta_file;

    int HO_degree, N;

    #ifdef RSC
    N = 1899;
    HO_degree = 3;
    strcpy(network_type, "RSC");
    #endif // RSC
    #ifdef HGMRI
    N = 2000;
    HO_degree = 7; // 15
    strcpy(network_type, "HGMRI");
    #endif // HGMRI
    #ifdef HG // For networks with varying inclusiveness
    N = 1899;
    HO_degree = 3;
    strcpy(network_type, "HG");
    #endif // HG

    beta_min = 0.0;
    beta_max = 2.01;
    delta_beta = 0.01;

    lmbda_min = 0.0;
    lmbda_max = 20.01;
    delta_lmbda = 0.01;

    char filename[100], header_string[HEADER_LENGTH];
    FILE *fin, *fout;
    sprintf(filename, "results/%s_%d_d=%d_opinions.txt", network_type, N, HO_degree);
    fout = fopen(filename, "wt");
    
    printf("Saving data in %s\n", filename);
 

    header = 0;
    for(beta = beta_min; beta<beta_max + delta_beta/2; beta += delta_beta)
    {
        for(lmbda=lmbda_min; lmbda<lmbda_max + delta_lmbda/2.; lmbda += delta_lmbda){
            sprintf(filename, "results/%s_%d_d=%d_opinions_l=%.2lf_b=%.2lf.txt", network_type, N, HO_degree, lmbda, beta);
            fin = fopen(filename, "rt");

            if(fin != NULL){
                for(i=0; i<20; i++){ // Reproducing header from the first file read into the final joint file
                    fgets(header_string, HEADER_LENGTH, fin);
                    if(header == 0){
                        printf("%s", header_string);
                        fprintf(fout, "%s", header_string);
                    }
                }
                header = 1; // We only copy the first header
                
                while(fscanf(fin, "%lf %lf %lf %d %d %lf %lf %lf", &lmbda_file, &lmbda_T_file, &beta_file, &stat, &N_steps, &mean_opinion, &dev_opinion, &exposure) != EOF){
                    fprintf(fout, "%lf %lf %lf %d %d %lf %lf %lf\n", lmbda_file, lmbda_T_file, beta_file, stat, N_steps, mean_opinion, dev_opinion, exposure);
                }
                
                fclose(fin);
            }
        }
    }
    
    fclose(fout);

    return 0;
}
